spring:
  datasource:
    url: jdbc:mysql://localhost:3306/project-management-test?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: "root"