spring:
  application:
    name: geektime-ddd
  datasource:
    url: jdbc:mysql://localhost:3306/project-management?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: "root"

logging:
  config: classpath:log4j2-local.xml

#mybatis:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl